sword-engine/config/routes.rb
Rails::Application.routes.draw do |map|
  resources :pages

  resources :sites

  resources :gadgets

  resources :positions

  resources :users
  resources :themes

  resources :roles
  resources :components
  resources :menus
  resources :operations

  root :to => "pages#index", :layout => "home"

end

sword-engine/app/models/component.rb
class Component < ActiveRecord::Base
  validates_presence_of   :name, :context, :description, :controller
  validates_uniqueness_of :name, :scope => [ :context ]
  validates_uniqueness_of :controller
  
  has_many :operations, :dependent => :destroy

  serialize :options

  def create_actions( *actions )
    actions.each{|action|
      Operation.create!( :component_id => self.id, :action => action.to_s, 
                        :description => "#{self.controller}##{action}")
    }
  end

  def create_menu( fields, description, action = "index" )
    operation = Operation.first( :conditions => { :action => action, :component_id => self.id } )
    options = { 
      :controller => self.controller,
      :action => action 
    }
    Menu.create_menu( fields, options, operation, description  )
  end

end

sword-engine/app/models/content.rb
class Content < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/content_type.rb
class ContentType < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/gadget.rb
class Gadget < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/menu.rb
class Menu < ActiveRecord::Base
  
  validates_presence_of   :name, :description, :options, :operation_id 
  validates_uniqueness_of :name, :scope => [ :parent_menu_id ]
  
  belongs_to :parent_menu, :class_name => "Menu"
  has_many   :child_menus, :class_name => "Menu", :foreign_key => :parent_menu_id

  serialize :options 


  def self.create_menu( fields, options, operation, description )
    menu = nil
    fields.each{|field|
      parent_menu_id = menu ? menu.id : nil
      menu = Menu.where( :parent_menu_id => parent_menu_id ).find_by_name( field ) ||
        Menu.create!( :name => field, :description => description, 
                     :url => nil, :options => options,
                     :parent_menu_id => parent_menu_id,
                     :operation_id => operation.id )
    }
    return menu
  end

end

sword-engine/app/models/operation.rb
class Operation < ActiveRecord::Base
  validates_presence_of   :component_id, :action, :description
  validates_uniqueness_of :component_id, :scope => [ :action ]

  has_many :menus, :dependent => :destroy
  has_many :roles, :class_name => "OperationRoleMap", :foreign_key => "operation_id", 
   :dependent => :destroy

  def self.get_operation( controller, action )
    component = Component.find_by_controller( controller )
    if( component )
      Operation.where( :component_id => component.id, :action => action ).first
    else
      nil
    end
  end
end

sword-engine/app/models/page.rb
class Page < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/page_role_map.rb
class PageRoleMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/position.rb
class Position < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/role.rb
class Role < ActiveRecord::Base
  validates_presence_of   :name, :description
  validates_uniqueness_of :name 

end

sword-engine/app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :theme

  serialize :options
  serialize :theme_options
  

  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_page_map.rb
class SitePageMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_role_map.rb
class SiteRoleMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_template.rb
class SiteTemplate < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/theme.rb
class Theme < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/user.rb
class User < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/controllers/positions_controller.rb
class PositionsController < SwordEngineApplicationController
  # GET /positions
  # GET /positions.xml
  def index
    @positions = Position.paginate :page => params[:page], :order => 'created_at DESC'
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.xml
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.xml
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.xml
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to(@position, :notice => 'Position was successfully created.') }
        format.xml  { render :xml => @position, :status => :created, :location => @position }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.xml
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to(@position, :notice => 'Position was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @position.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.xml
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to(positions_url) }
      format.xml  { head :ok }
    end
  end
end

sword-engine/app/helpers/menus_helper.rb
module MenusHelper
end

sword-engine/app/helpers/pages_helper.rb
module PagesHelper
end

sword-engine/app/helpers/positions_helper.rb
module PositionsHelper
end

sword-engine/app/helpers/roles_helper.rb
module RolesHelper
end

sword-engine/app/helpers/sites_helper.rb
module SitesHelper
end

sword-engine/app/helpers/users_helper.rb
module UsersHelper
end

sword-engine/app/views/positions/_default.css.erb
/* Stylesheet for the Component Position */

sword-engine/app/views/positions/_default.js.erb
/* Javascript for the Component Position */

sword-engine/app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_position_id %><br />
    <%= f.text_field :parent_position_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_area :options %>
  </div>
  <div class="field">
    <%= f.label :frozen_position %><br />
    <%= f.check_box :frozen_position %>
  </div>
  <div class="field">
    <%= f.label :sort_value %><br />
    <%= f.text_field :sort_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sword-engine/app/views/positions/_menu.html.erb
<%= f.hidden_field :controller %>

sword-engine/app/views/positions/_options.html.erb
<div class="field">
  <%= f.label  :max_retry %><br />
  <%= f.text_field, :max_retry %>
</div>

sword-engine/app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

sword-engine/app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table class='listview' >
  <thead>
    <tr>
        <th>Name</th>
        <th>Parent position</th>
        <th>Description</th>
        <th>Options</th>
        <th>Frozen position</th>
        <th>Sort value</th>
        <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.name %></td>
    <td><%= position.parent_position_id %></td>
    <td><%= position.description %></td>
    <td><%= position.options %></td>
    <td><%= position.frozen_position %></td>
    <td><%= position.sort_value %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

  </tbody>
  <tfoot>
    <tr><td colspan=6 > <%= will_paginate @positions %> </td></tr>
  </tfoot>

</table>

<br />

<%= link_to 'New Position', new_position_path %>

sword-engine/app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

sword-engine/app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @position.name %>
</p>

<p>
  <b>Parent position:</b>
  <%= @position.parent_position_id %>
</p>

<p>
  <b>Description:</b>
  <%= @position.description %>
</p>

<p>
  <b>Options:</b>
  <%= @position.options %>
</p>

<p>
  <b>Frozen position:</b>
  <%= @position.frozen_position %>
</p>

<p>
  <b>Sort value:</b>
  <%= @position.sort_value %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>