sword-engine/config/routes.rb
Rails::Application.routes.draw do |map|
  resources :pages

  resources :sites

  resources :gadgets

  resources :positions

  resources :users
  resources :themes

  resources :roles
  resources :components
  resources :menus
  resources :operations

  root :to => "pages#index", :layout => "home"

end

sword-engine/app/models/component.rb
class Component < ActiveRecord::Base
  validates_presence_of   :name, :context, :description, :controller
  validates_uniqueness_of :name, :scope => [ :context ]
  validates_uniqueness_of :controller
  
  has_many :operations, :dependent => :destroy

  serialize :options

  def create_actions( *actions )
    actions.each{|action|
      Operation.create!( :component_id => self.id, :action => action.to_s, 
                        :description => "#{self.controller}##{action}")
    }
  end

  def create_menu( fields, description, action = "index" )
    operation = Operation.first( :conditions => { :action => action, :component_id => self.id } )
    options = { 
      :controller => self.controller,
      :action => action 
    }
    Menu.create_menu( fields, options, operation, description  )
  end

end

sword-engine/app/models/content.rb
class Content < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/content_type.rb
class ContentType < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/gadget.rb
class Gadget < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/menu.rb
class Menu < ActiveRecord::Base
  
  validates_presence_of   :name, :description, :options, :operation_id 
  validates_uniqueness_of :name, :scope => [ :parent_menu_id ]
  
  belongs_to :parent_menu, :class_name => "Menu"
  has_many   :child_menus, :class_name => "Menu", :foreign_key => :parent_menu_id

  serialize :options 


  def self.create_menu( fields, options, operation, description )
    menu = nil
    fields.each{|field|
      parent_menu_id = menu ? menu.id : nil
      menu = Menu.where( :parent_menu_id => parent_menu_id ).find_by_name( field ) ||
        Menu.create!( :name => field, :description => description, 
                     :url => nil, :options => options,
                     :parent_menu_id => parent_menu_id,
                     :operation_id => operation.id )
    }
    return menu
  end

end

sword-engine/app/models/operation.rb
class Operation < ActiveRecord::Base
  validates_presence_of   :component_id, :action, :description
  validates_uniqueness_of :component_id, :scope => [ :action ]

  has_many :menus, :dependent => :destroy
  has_many :roles, :class_name => "OperationRoleMap", :foreign_key => "operation_id", 
   :dependent => :destroy

  def self.get_operation( controller, action )
    component = Component.find_by_controller( controller )
    if( component )
      Operation.where( :component_id => component.id, :action => action ).first
    else
      nil
    end
  end
end

sword-engine/app/models/page.rb
class Page < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/page_role_map.rb
class PageRoleMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/position.rb
class Position < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/role.rb
class Role < ActiveRecord::Base
  validates_presence_of   :name, :description
  validates_uniqueness_of :name 

end

sword-engine/app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :theme

  serialize :options
  serialize :theme_options
  

  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_page_map.rb
class SitePageMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_role_map.rb
class SiteRoleMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_template.rb
class SiteTemplate < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/theme.rb
class Theme < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/user.rb
class User < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/controllers/operations_controller.rb
class OperationsController < SwordEngineApplicationController
  # GET /operations
  # GET /operations.xml
  def index
    @operations = Operation.paginate :page => params[:page], :order => 'created_at DESC'
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @operations }
    end
  end

  # GET /operations/1
  # GET /operations/1.xml
  def show
    @operation = Operation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @operation }
    end
  end

  # GET /operations/new
  # GET /operations/new.xml
  def new
    @operation = Operation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @operation }
    end
  end

  # GET /operations/1/edit
  def edit
    @operation = Operation.find(params[:id])
  end

  # POST /operations
  # POST /operations.xml
  def create
    @operation = Operation.new(params[:operation])

    respond_to do |format|
      if @operation.save
        format.html { redirect_to(@operation, :notice => 'Operation was successfully created.') }
        format.xml  { render :xml => @operation, :status => :created, :location => @operation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /operations/1
  # PUT /operations/1.xml
  def update
    @operation = Operation.find(params[:id])

    respond_to do |format|
      if @operation.update_attributes(params[:operation])
        format.html { redirect_to(@operation, :notice => 'Operation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @operation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.xml
  def destroy
    @operation = Operation.find(params[:id])
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to(operations_url) }
      format.xml  { head :ok }
    end
  end
end

sword-engine/app/helpers/menus_helper.rb
module MenusHelper
end

sword-engine/app/helpers/operations_helper.rb
module OperationsHelper
end

sword-engine/app/helpers/pages_helper.rb
module PagesHelper
end

sword-engine/app/helpers/roles_helper.rb
module RolesHelper
end

sword-engine/app/helpers/sites_helper.rb
module SitesHelper
end

sword-engine/app/helpers/users_helper.rb
module UsersHelper
end

sword-engine/app/views/operations/_default.css.erb
/* Stylesheet for the Component Operation */

sword-engine/app/views/operations/_default.js.erb
/* Javascript for the Component Operation */

sword-engine/app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :component_id %><br />
    <%= f.text_field :component_id %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sword-engine/app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

sword-engine/app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table class='listview' >
  <thead>
    <tr>
        <th>Component</th>
        <th>Action</th>
        <th>Description</th>
        <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<% @operations.each do |operation| %>
  <tr>
    <td><%= operation.component_id %></td>
    <td><%= operation.action %></td>
    <td><%= operation.description %></td>
    <td><%= link_to 'Show', operation %></td>
    <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
    <td><%= link_to 'Destroy', operation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

  </tbody>
  <tfoot>
    <tr><td colspan=3 > <%= will_paginate @operations %> </td></tr>
  </tfoot>

</table>

<br />

<%= link_to 'New Operation', new_operation_path %>

sword-engine/app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

sword-engine/app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Component:</b>
  <%= @operation.component_id %>
</p>

<p>
  <b>Action:</b>
  <%= @operation.action %>
</p>

<p>
  <b>Description:</b>
  <%= @operation.description %>
</p>


<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>