sword-engine/config/routes.rb
Rails::Application.routes.draw do |map|
  resources :pages

  resources :sites

  resources :gadgets

  resources :positions

  resources :users
  resources :themes

  resources :roles
  resources :components
  resources :menus
  resources :operations

  root :to => "pages#index", :layout => "home"

end

sword-engine/app/models/component.rb
class Component < ActiveRecord::Base
  validates_presence_of   :name, :context, :description, :controller
  validates_uniqueness_of :name, :scope => [ :context ]
  validates_uniqueness_of :controller
  
  has_many :operations, :dependent => :destroy

  serialize :options

  def create_actions( *actions )
    actions.each{|action|
      Operation.create!( :component_id => self.id, :action => action.to_s, 
                        :description => "#{self.controller}##{action}")
    }
  end

  def create_menu( fields, description, action = "index" )
    operation = Operation.first( :conditions => { :action => action, :component_id => self.id } )
    options = { 
      :controller => self.controller,
      :action => action 
    }
    Menu.create_menu( fields, options, operation, description  )
  end

end

sword-engine/app/models/content.rb
class Content < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/content_type.rb
class ContentType < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/gadget.rb
class Gadget < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/menu.rb
class Menu < ActiveRecord::Base
  
  validates_presence_of   :name, :description, :options, :operation_id 
  validates_uniqueness_of :name, :scope => [ :parent_menu_id ]
  
  belongs_to :parent_menu, :class_name => "Menu"
  has_many   :child_menus, :class_name => "Menu", :foreign_key => :parent_menu_id

  serialize :options 


  def self.create_menu( fields, options, operation, description )
    menu = nil
    fields.each{|field|
      parent_menu_id = menu ? menu.id : nil
      menu = Menu.where( :parent_menu_id => parent_menu_id ).find_by_name( field ) ||
        Menu.create!( :name => field, :description => description, 
                     :url => nil, :options => options,
                     :parent_menu_id => parent_menu_id,
                     :operation_id => operation.id )
    }
    return menu
  end

end

sword-engine/app/models/operation.rb
class Operation < ActiveRecord::Base
  validates_presence_of   :component_id, :action, :description
  validates_uniqueness_of :component_id, :scope => [ :action ]

  has_many :menus, :dependent => :destroy
  has_many :roles, :class_name => "OperationRoleMap", :foreign_key => "operation_id", 
   :dependent => :destroy

  def self.get_operation( controller, action )
    component = Component.find_by_controller( controller )
    if( component )
      Operation.where( :component_id => component.id, :action => action ).first
    else
      nil
    end
  end
end

sword-engine/app/models/page.rb
class Page < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/page_role_map.rb
class PageRoleMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/position.rb
class Position < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/role.rb
class Role < ActiveRecord::Base
  validates_presence_of   :name, :description
  validates_uniqueness_of :name 

end

sword-engine/app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :theme

  serialize :options
  serialize :theme_options
  

  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_page_map.rb
class SitePageMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_role_map.rb
class SiteRoleMap < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/site_template.rb
class SiteTemplate < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/theme.rb
class Theme < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/models/user.rb
class User < ActiveRecord::Base


  cattr_reader :per_page
  @@per_page = 10
end

sword-engine/app/controllers/themes_controller.rb
class ThemesController < SwordEngineApplicationController
  # GET /themes
  # GET /themes.xml
  def index
    @themes = Theme.paginate :page => params[:page], :order => 'created_at DESC'
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @themes }
    end
  end

  # GET /themes/1
  # GET /themes/1.xml
  def show
    @theme = Theme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @theme }
    end
  end

  # GET /themes/new
  # GET /themes/new.xml
  def new
    @theme = Theme.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @theme }
    end
  end

  # GET /themes/1/edit
  def edit
    @theme = Theme.find(params[:id])
  end

  # POST /themes
  # POST /themes.xml
  def create
    @theme = Theme.new(params[:theme])

    respond_to do |format|
      if @theme.save
        format.html { redirect_to(@theme, :notice => 'Theme was successfully created.') }
        format.xml  { render :xml => @theme, :status => :created, :location => @theme }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @theme.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /themes/1
  # PUT /themes/1.xml
  def update
    @theme = Theme.find(params[:id])

    respond_to do |format|
      if @theme.update_attributes(params[:theme])
        format.html { redirect_to(@theme, :notice => 'Theme was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @theme.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.xml
  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to(themes_url) }
      format.xml  { head :ok }
    end
  end
end

sword-engine/app/helpers/menus_helper.rb
module MenusHelper
end

sword-engine/app/helpers/pages_helper.rb
module PagesHelper
end

sword-engine/app/helpers/roles_helper.rb
module RolesHelper
end

sword-engine/app/helpers/sites_helper.rb
module SitesHelper
end

sword-engine/app/helpers/themes_helper.rb
module ThemesHelper
end

sword-engine/app/helpers/users_helper.rb
module UsersHelper
end

sword-engine/app/views/layouts/themes/simple/default.html.erb
<html> 
  <head> 
    <title> <%= @current_site.options.name %> | Default </title> 
    <%= javascript_include_tag :defaults %> 
    <%= javascript_include_tag '/themes/simple/js/default.js' %>
    <%= stylesheet_link_tag '/themes/simple/css/default.css' %>
  </head>
  <body>
    <div>
      Default Header
    </div>
    <div>
      <%= yield %>
    </div>
    <div>
      Footer
    </div>
  </body>
</html>
    

sword-engine/app/views/layouts/themes/simple/home.html.erb
<html> 
  <head> 
    <title> <%= @current_site.options.name %> | Home </title> 
    <%= javascript_include_tag :defaults %> 
    <%= javascript_include_tag '/themes/simple/js/default.js' %>
    <%= stylesheet_link_tag '/themes/simple/css/default.css' %>
  </head>
  <body>
    <div>
      Home Header
    </div>
    <div>
      <%= yield %>
    </div>
    <div>
      Footer
    </div>
  </body>
</html>
    

sword-engine/app/views/layouts/themes/simple/login.html.erb
<html> 
  <head> 
    <title> <%= @current_site.options.name %> | Login </title> 
    <%= javascript_include_tag :defaults %> 
    <%= javascript_include_tag '/themes/simple/js/default.js' %>
    <%= stylesheet_link_tag '/themes/simple/css/default.css' %>
  </head>
  <body>
    <div>
      Login Header
    </div>
    <div>
      <%= yield %>
    </div>
    <div>
      Footer
    </div>
  </body>
</html>
    

sword-engine/app/views/layouts/themes/simple/print.html.erb
<html> 
  <head> 
    <title> <%= @current_site.options.name %> | Print </title> 
    <%= javascript_include_tag :defaults %> 
    <%= javascript_include_tag '/themes/simple/js/default.js' %>
    <%= stylesheet_link_tag '/themes/simple/css/default.css' %>
  </head>
  <body>
    <div>
      Print Header
    </div>
    <div>
      <%= yield %>
    </div>
    <div>
      Footer
    </div>
  </body>
</html>
    

sword-engine/app/views/themes/_default.css.erb
/* Stylesheet for the Component Theme */

sword-engine/app/views/themes/_default.js.erb
/* Javascript for the Component Theme */

sword-engine/app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
  <% if @theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% @theme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_area :options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sword-engine/app/views/themes/_menu.html.erb
<%= f.hidden_field :controller %>

sword-engine/app/views/themes/_options.html.erb
<div class="field">
  <%= f.label  :max_retry %><br />
  <%= f.text_field, :max_retry %>
</div>

sword-engine/app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

sword-engine/app/views/themes/index.html.erb
<h1>Listing themes</h1>

<table class='listview' >
  <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Options</th>
        <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<% @themes.each do |theme| %>
  <tr>
    <td><%= theme.name %></td>
    <td><%= theme.description %></td>
    <td><%= theme.options %></td>
    <td><%= link_to 'Show', theme %></td>
    <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
    <td><%= link_to 'Destroy', theme, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

  </tbody>
  <tfoot>
    <tr><td colspan=3 > <%= will_paginate @themes %> </td></tr>
  </tfoot>

</table>

<br />

<%= link_to 'New Theme', new_theme_path %>

sword-engine/app/views/themes/new.html.erb
<h1>New theme</h1>

<%= render 'form' %>

<%= link_to 'Back', themes_path %>

sword-engine/app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @theme.name %>
</p>

<p>
  <b>Description:</b>
  <%= @theme.description %>
</p>

<p>
  <b>Options:</b>
  <%= @theme.options %>
</p>


<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>